name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - main
      - master
    paths:
      - "backend/**"
      - ".github/workflows/backend-CICD.yml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-CICD.yml"
      

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} \
            --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ secrets.REGISTRY_LOGIN_SERVER }}/fastapi-playwright:$(date +%Y%m%d%H%M%S)
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
          docker build -t $IMAGE_NAME -f backend/Dockerfile

      - name: Push Docker image to ACR
        run: |
          docker push $IMAGE_NAME
