name: Deploy Frontend to Azure App Container

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . -f ./frontend/Dockerfile -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/freelancer-toolkit-frontend:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/freelancer-toolkit-frontend:${{ github.sha }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          azure-container-registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          azure-container-app-name: YOUR_CONTAINER_APP_NAME
          resource-group: YOUR_RESOURCE_GROUP
          container-image-name: ${{ secrets.REGISTRY_LOGIN_SERVER }}/freelancer-toolkit-frontend:${{ github.sha }}
